// <auto-generated />
using System;
using BloomWatch.Modules.WatchSpaces.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BloomWatch.Modules.WatchSpaces.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WatchSpacesDbContext))]
    partial class WatchSpacesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("watch_spaces")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BloomWatch.Modules.WatchSpaces.Domain.Aggregates.WatchSpace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("watch_spaces", "watch_spaces");
                });

            modelBuilder.Entity("BloomWatch.Modules.WatchSpaces.Domain.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_user_id");

                    b.Property<string>("InvitedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("invited_email");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token");

                    b.Property<Guid>("WatchSpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("watch_space_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_invitations_token");

                    b.HasIndex("WatchSpaceId");

                    b.ToTable("invitations", "watch_spaces");
                });

            modelBuilder.Entity("BloomWatch.Modules.WatchSpaces.Domain.Entities.WatchSpaceMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WatchSpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("watch_space_id");

                    b.HasKey("Id");

                    b.HasIndex("WatchSpaceId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_watch_space_members_space_user");

                    b.ToTable("watch_space_members", "watch_spaces");
                });

            modelBuilder.Entity("BloomWatch.Modules.WatchSpaces.Domain.Entities.Invitation", b =>
                {
                    b.HasOne("BloomWatch.Modules.WatchSpaces.Domain.Aggregates.WatchSpace", null)
                        .WithMany("_invitations")
                        .HasForeignKey("WatchSpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BloomWatch.Modules.WatchSpaces.Domain.Entities.WatchSpaceMember", b =>
                {
                    b.HasOne("BloomWatch.Modules.WatchSpaces.Domain.Aggregates.WatchSpace", null)
                        .WithMany("_members")
                        .HasForeignKey("WatchSpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BloomWatch.Modules.WatchSpaces.Domain.Aggregates.WatchSpace", b =>
                {
                    b.Navigation("_invitations");

                    b.Navigation("_members");
                });
#pragma warning restore 612, 618
        }
    }
}
