// <auto-generated />
using System;
using BloomWatch.Modules.AnimeTracking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BloomWatch.Modules.AnimeTracking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AnimeTrackingDbContext))]
    [Migration("20260318133913_AddWatchSessionsTable")]
    partial class AddWatchSessionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("anime_tracking")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BloomWatch.Modules.AnimeTracking.Domain.Aggregates.WatchSpaceAnime", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at_utc");

                    b.Property<Guid>("AddedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by_user_id");

                    b.Property<int>("AniListMediaId")
                        .HasColumnType("integer")
                        .HasColumnName("anilist_media_id");

                    b.Property<string>("CoverImageUrlSnapshot")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("cover_image_url_snapshot");

                    b.Property<int?>("EpisodeCountSnapshot")
                        .HasColumnType("integer")
                        .HasColumnName("episode_count_snapshot");

                    b.Property<string>("Format")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("format");

                    b.Property<string>("Mood")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mood");

                    b.Property<string>("Pitch")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pitch");

                    b.Property<string>("PreferredTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("preferred_title");

                    b.Property<string>("Season")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("season");

                    b.Property<int?>("SeasonYear")
                        .HasColumnType("integer")
                        .HasColumnName("season_year");

                    b.Property<int>("SharedEpisodesWatched")
                        .HasColumnType("integer")
                        .HasColumnName("shared_episodes_watched");

                    b.Property<string>("SharedStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shared_status");

                    b.Property<string>("Vibe")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("vibe");

                    b.Property<Guid>("WatchSpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("watch_space_id");

                    b.HasKey("Id");

                    b.HasIndex("WatchSpaceId", "AniListMediaId")
                        .IsUnique()
                        .HasDatabaseName("ix_watch_space_anime_space_media");

                    b.ToTable("watch_space_anime", "anime_tracking");
                });

            modelBuilder.Entity("BloomWatch.Modules.AnimeTracking.Domain.Entities.ParticipantEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("EpisodesWatched")
                        .HasColumnType("integer")
                        .HasColumnName("episodes_watched");

                    b.Property<string>("IndividualStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("individual_status");

                    b.Property<DateTime>("LastUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at_utc");

                    b.Property<string>("RatingNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rating_notes");

                    b.Property<decimal?>("RatingScore")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("rating_score");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WatchSpaceAnimeId")
                        .HasColumnType("uuid")
                        .HasColumnName("watch_space_anime_id");

                    b.HasKey("Id");

                    b.HasIndex("WatchSpaceAnimeId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_participant_entries_anime_user");

                    b.ToTable("participant_entries", "anime_tracking");
                });

            modelBuilder.Entity("BloomWatch.Modules.AnimeTracking.Domain.Entities.WatchSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("EndEpisode")
                        .HasColumnType("integer")
                        .HasColumnName("end_episode");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("SessionDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("session_date_utc");

                    b.Property<int>("StartEpisode")
                        .HasColumnType("integer")
                        .HasColumnName("start_episode");

                    b.Property<Guid>("WatchSpaceAnimeId")
                        .HasColumnType("uuid")
                        .HasColumnName("watch_space_anime_id");

                    b.HasKey("Id");

                    b.HasIndex("WatchSpaceAnimeId")
                        .HasDatabaseName("ix_watch_sessions_anime");

                    b.ToTable("watch_sessions", "anime_tracking");
                });

            modelBuilder.Entity("BloomWatch.Modules.AnimeTracking.Domain.Entities.ParticipantEntry", b =>
                {
                    b.HasOne("BloomWatch.Modules.AnimeTracking.Domain.Aggregates.WatchSpaceAnime", null)
                        .WithMany("ParticipantEntries")
                        .HasForeignKey("WatchSpaceAnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BloomWatch.Modules.AnimeTracking.Domain.Entities.WatchSession", b =>
                {
                    b.HasOne("BloomWatch.Modules.AnimeTracking.Domain.Aggregates.WatchSpaceAnime", null)
                        .WithMany("WatchSessions")
                        .HasForeignKey("WatchSpaceAnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BloomWatch.Modules.AnimeTracking.Domain.Aggregates.WatchSpaceAnime", b =>
                {
                    b.Navigation("ParticipantEntries");

                    b.Navigation("WatchSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
