// <auto-generated />
using System;
using System.Collections.Generic;
using BloomWatch.Modules.AniListSync.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BloomWatch.Modules.AniListSync.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AniListSyncDbContext))]
    [Migration("20260316200931_InitialMediaCache")]
    partial class InitialMediaCache
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("anilist_sync")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BloomWatch.Modules.AniListSync.Domain.Entities.MediaCacheEntry", b =>
                {
                    b.Property<int>("AnilistMediaId")
                        .HasColumnType("integer")
                        .HasColumnName("anilist_media_id");

                    b.Property<int?>("AverageScore")
                        .HasColumnType("integer")
                        .HasColumnName("average_score");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cached_at");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("cover_image_url");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("Episodes")
                        .HasColumnType("integer")
                        .HasColumnName("episodes");

                    b.Property<string>("Format")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("format");

                    b.PrimitiveCollection<IReadOnlyList<string>>("Genres")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("genres");

                    b.Property<int?>("Popularity")
                        .HasColumnType("integer")
                        .HasColumnName("popularity");

                    b.Property<string>("Season")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("season");

                    b.Property<int?>("SeasonYear")
                        .HasColumnType("integer")
                        .HasColumnName("season_year");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TitleEnglish")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title_english");

                    b.Property<string>("TitleNative")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title_native");

                    b.Property<string>("TitleRomaji")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title_romaji");

                    b.HasKey("AnilistMediaId");

                    b.ToTable("media_cache", "anilist_sync");
                });
#pragma warning restore 612, 618
        }
    }
}
